input {
  # Lắng nghe log gửi qua giao thức TCP dưới dạng JSON
  tcp {
    port => 5049
    codec => json
  }
}

filter {
  # Tự động lấy mốc thời gian từ log của Python làm mốc thời gian chuẩn trong ELK
  if [timestamp] {
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  }
}

output {
  # Đẩy dữ liệu sau khi lọc vào Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "coingecko-pipeline-logs-%{+YYYY.MM.dd}"
  }
  
  # Đồng thời in ra màn hình container để tiện theo dõi (Debug)
  stdout { codec => rubydebug }
}